### ISSUE TITLE
Decyzje projektowe

### ISSUE THREAD

**Issue by moozeq** [moozeq/PSZT_EVO#5]
Trzeba podjąć decyzje projektowe co do:

- Z jakiego zakresu losujemy sigme u pierwszej populacji?
- Kiedy stop algorytmu? Bo jeśli algorytm ma być uniwersalny to warunek stopu też powinien: wtedy są 2 opcje, które mozna implementować razem, albo po N iteracjach, albo gdy najlepszy potomek przez K iteracji się nie zmienia. Wtedy trzeba wybrać też N i K. Drugie podejście to wiemy, że w naszym problemie funkcja maximum ma wtedy gdy iloczyn cosinusow = 1, a ujemna część = 0. Wtedy warunek, że np. najlepszy potomek ma mieć fitting na poziomie 0.95 wystarczy.
- W jaki sposób wybieramy λ-elementową populację T z P? W pełni losowo? W zależności od fittingu?

**Comment by Smomic** [comment]
Odnośnie zakresu sigm to najlepsze byłoby stopniowe zawężanie, nie wiem tylko, jak sprawdzało by się to w praktyce. Z drugim punktem to zostawiłbym tak jak jest, czyli ten poziom 0.95, co do trzeciego to można by zrobić selekcję rankingową, powinna być dość efektywna.

**Comment by moozeq** [comment]
Co do tego losowania populacji T z P, to właśnie w skrypcie przeczytałem: "Kolejne osobniki znajdują się w niej przez losowanie ze zwracaniem z P, zaś kolejne pary tej sekwencji będą stanowiły rodziców osobników z nowej populacji." więc ten problem się rozwiązał, selekcja rankingowa jest dopiero przy wyborze nowej populacji z P+R.

Co do tego poziomu 0.95 to może być to + ilość maksymalnych iteracji żeby w razie zapętlenia w słabych maksimach lokalnych nie zapętlił się algorytm.
